# SAM CLI configuration file
version = 0.1

[default.global.parameters]
stack_name = "datafusion-fiddle"
resolve_s3 = true

[default.build.parameters]
parallel = true
cached = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=dev"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=staging"

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=prod"

[default.local_start_api.parameters]
warm_containers = "EAGER"
port = 3001